ShopMart:
  outputs:
    dev:
      account: afwdjhf-fz93309
      database: SHOPSMART_DBT
      password: Santosh1234567890
      role: ACCOUNTADMIN
      schema: ENT
      threads: 1
      type: snowflake
      user: spani
      warehouse: COMPUTE_WH
      client_session_keep_alive: False
  target: dev
